# # apiVersion: apps/v1
# # kind: Deployment
# # metadata:
# #   name: frontend-deployment
# #   namespace: wanderlust
# #   labels:
# #     app: frontend
# # spec:
# #   replicas: 1
# #   selector:
# #     matchLabels:
# #       app: frontend
# #   template:
# #     metadata:
# #       name: frontend
# #       labels:
# #         app: frontend
# #     spec:
# #       containers:
# #         - name: frontend
# #           image: rithwik504/wanderlust-frontend-beta:v1
# #           ports:
# #             - containerPort: 5173
# # ---
# # apiVersion: v1
# # kind: Service
# # metadata:
# #   name: frontend-service
# #   namespace: wanderlust
# # spec:
# #   type: LoadBalancer
# #   selector:
# #     app: frontend
# #   ports:
# #     - port: 5173
# #       targetPort: 5173
# #       protocol: TCP
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: frontend-deployment
#   namespace: wanderlust
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: frontend
#   template:
#     metadata:
#       labels:
#         app: frontend
#     spec:
#       containers:
#         - name: frontend
#           image: zeeshanshaikh799/wanderlust-frontend:v1.1
#           imagePullPolicy: Always
#           ports:
#             - containerPort: 80
# ---
# # apiVersion: v1
# # kind: Service
# # metadata:
# #   name: frontend-service
# #   namespace: wanderlust
# # spec:
# #   type: LoadBalancer
# #   selector:
# #     app: frontend
# #   ports:
# #     - port: 80
# #       targetPort: 80
# #       protocol: TCP


# apiVersion: v1
# kind: Service
# metadata:
#   name: frontend-service
#   namespace: wanderlust
# spec:
#   type: ClusterIP
#   selector:
#     app: frontend
#   ports:
#     - port: 80
#       targetPort: 80














apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: wanderlust
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: zeeshanshaikh799/wanderlust:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: wanderlust
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
